### ISSUE TITLE
Formatting doesn't play nice with split windows

### ISSUE THREAD

**Issue by Dennis12Hahn** [SaidShah/extreme-coding-school#1]
OS: Ubuntu (GNOME desktop environment)
Browser: Chromium
Display Size: 15.6"
Display Resolution: 3840x2160
![Screenshot from 2019-04-02 22-32-49](https://user-images.githubusercontent.com/31702540/55449293-ec569d00-5598-11e9-902d-47cf2b48c335.png)

**Comment by battlebutts** [comment]
Fixed as of commit c39f1b8
