### ISSUE TITLE
Finish phone course descriptions

### ISSUE THREAD

**Issue by kumquatfelafel** [SaidShah/extreme-coding-school#2]
The phone course descriptions in Courses do not match (computer) website course descriptions(I assume intentional? If unintentional, must fix)

More to the point though, the Full Stack Web Development Bootcamp and Data Structures and Algorithms with Java courses currently (at least on official site) use the React/Redux course description. Must be modified to reflect accurate description.

- [x] Add Full Stack Web Development Bootcamp course description (in Courses)
- [x] Add Data Structures and Algorithms with Java course description (in Courses)
- [x] Add Intro to Java course description
- [ ] Update descriptions on mobile version

**Comment by battlebutts** [comment]
The mobile course descriptions were intended to be temporary, so we'll fix this on _thursday_
