### ISSUE TITLE
Ginormous whitespace in https://extremecodingschool.com/courses/frontend on computer

### ISSUE THREAD

**Issue by kumquatfelafel** [SaidShah/extreme-coding-school#3]
above

![Screen Shot 2019-04-03 at 9 50 02 AM](https://user-images.githubusercontent.com/29548108/55484271-34f07380-55f6-11e9-8638-1f394f08543e.png)

and below

![Screen Shot 2019-04-03 at 9 50 21 AM](https://user-images.githubusercontent.com/29548108/55484285-3b7eeb00-55f6-11e9-89ef-5cf6c83a0854.png)

Proposed to do list:
- [ ] Fix massive space in safari browser version?
- [ ] Fix alignment problem in firefox version? (see below)

**Comment by kumquatfelafel** [comment]
Normal zoom. Appears perfectly fine on phone in both portrait and landscape. Appears to be safari specific problem.

**Comment by battlebutts** [comment]
Fixed as of commit 38c2566
